ở(hoa,nhatrang).
ba(định,hoa).
mẹ(thanh,hoa).
giáoviên(định).
giáoviên(thanh).
dạycấp(định,cấp3).
dạycấp(thanh,cấp3).
dạymôn(định,toán).
dạymôn(thanh,sinhvật).
giỏi(định).
giỏi(thanh).
hiền(định).
hiền(thanh).
thích(hoa,toán).
thích(hoa,sinhvật).
vuivẻ(định).
vuivẻ(thanh).
vuivẻ(hoa).
thương(định,hoa).
thương(định,thanh).
thương(thanh,hoa).
thương(thanh,định).
thương(hoa,định).
thương(hoa,thanh).