từ_vựng(nam,0).
từ_vựng(hoa,0).
từ_vựng(nhatrang,0).
từ_vựng(khoa_học_máy_tính,0).
từ_vựng(hệ_thống_thông_tin,0).
từ_vựng(hệ_điều_hành,0).
từ_vựng(giải_tích,0).
từ_vựng(sinh_viên,1).
từ_vựng(chó,0).
từ_vựng(qua,2).
từ_vựng(công_viên,0).
từ_vựng(quen,2).
từ_vựng(định,0).
từ_vựng(thanh,0).
từ_vựng(cấp3,0).
từ_vựng(toán,0).
từ_vựng(sinh_học,0).
từ_vựng(ở,2).
từ_vựng(ba,2).
từ_vựng(mẹ,2).
từ_vựng(giáoviên,1).
từ_vựng(dạycấp,2).
từ_vựng(dạymôn,2).
từ_vựng(giỏi,1).
từ_vựng(hiền,1).
từ_vựng(thích,2).
từ_vựng(vuivẻ,1).
từ_vựng(thương,2).
từ_vựng(học,2).